// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/queue.proto

package queuepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnqueueJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueJobRequest) Reset() {
	*x = EnqueueJobRequest{}
	mi := &file_proto_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueJobRequest) ProtoMessage() {}

func (x *EnqueueJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueJobRequest.ProtoReflect.Descriptor instead.
func (*EnqueueJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_queue_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueJobRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EnqueueJobRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EnqueueJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueJobResponse) Reset() {
	*x = EnqueueJobResponse{}
	mi := &file_proto_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueJobResponse) ProtoMessage() {}

func (x *EnqueueJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueJobResponse.ProtoReflect.Descriptor instead.
func (*EnqueueJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_queue_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_proto_queue_proto protoreflect.FileDescriptor

const file_proto_queue_proto_rawDesc = "" +
	"\n" +
	"\x11proto/queue.proto\x12\x05queue\"A\n" +
	"\x11EnqueueJobRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"+\n" +
	"\x12EnqueueJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId2Q\n" +
	"\fQueueService\x12A\n" +
	"\n" +
	"EnqueueJob\x12\x18.queue.EnqueueJobRequest\x1a\x19.queue.EnqueueJobResponseB,Z*github.com/turnertastic1/boltq/pkg/queuepbb\x06proto3"

var (
	file_proto_queue_proto_rawDescOnce sync.Once
	file_proto_queue_proto_rawDescData []byte
)

func file_proto_queue_proto_rawDescGZIP() []byte {
	file_proto_queue_proto_rawDescOnce.Do(func() {
		file_proto_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_queue_proto_rawDesc), len(file_proto_queue_proto_rawDesc)))
	})
	return file_proto_queue_proto_rawDescData
}

var file_proto_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_queue_proto_goTypes = []any{
	(*EnqueueJobRequest)(nil),  // 0: queue.EnqueueJobRequest
	(*EnqueueJobResponse)(nil), // 1: queue.EnqueueJobResponse
}
var file_proto_queue_proto_depIdxs = []int32{
	0, // 0: queue.QueueService.EnqueueJob:input_type -> queue.EnqueueJobRequest
	1, // 1: queue.QueueService.EnqueueJob:output_type -> queue.EnqueueJobResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_queue_proto_init() }
func file_proto_queue_proto_init() {
	if File_proto_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_queue_proto_rawDesc), len(file_proto_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_queue_proto_goTypes,
		DependencyIndexes: file_proto_queue_proto_depIdxs,
		MessageInfos:      file_proto_queue_proto_msgTypes,
	}.Build()
	File_proto_queue_proto = out.File
	file_proto_queue_proto_goTypes = nil
	file_proto_queue_proto_depIdxs = nil
}
